export default {
    products: [{
            _id: "1",
            name: "Boring Company",
            category: "Diesel",
            image: "/Images/1.jpeg",
            price: 45,
            brand: "Counterbalance truck",
            rating: 4.5,
            numReviews: 1000,
            countInStock: 10,
        },
        {
            _id: "2",
            name: "Boring Company",
            category: "Diesel",
            image: "/Images/1.jpeg",
            price: 45,
            brand: "Counterbalance truck",
            rating: 4.5,
            numReviews: 1000,
            countInStock: 10,
        },
        {
            _id: "3",
            name: "Boring Company",
            category: "Diesel",
            image: "/Images/1.jpeg",
            price: 45,
            brand: "Counterbalance truck",
            rating: 4.5,
            numReviews: 1000,
            countInStock: 10,
        },
        {
            _id: "4",
            name: "Boring Company",
            category: "Diesel",
            image: "/Images/1.jpeg",
            price: 45,
            brand: "Counterbalance truck",
            rating: 4.5,
            numReviews: 1000,
            countInStock: 10,
        },
        {
            _id: "5",
            name: "Boring Company",
            category: "Diesel",
            image: "/Images/1.jpeg",
            price: 45,
            brand: "Counterbalance truck",
            rating: 4.5,
            numReviews: 1000,
            countInStock: 10,
        },
        {
            _id: "6",
            name: "Boring Company",
            category: "Diesel",
            image: "/Images/1.jpeg",
            price: 45,
            brand: "Counterbalance truck",
            rating: 4.5,
            numReviews: 1000,
            countInStock: 10,
        },
    ],
};